//#line 2 "/opt/ros/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the automow_fence_detection package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __automow_fence_detection__HOUGHFENCECONFIG_H__
#define __automow_fence_detection__HOUGHFENCECONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace automow_fence_detection
{
  class HoughFenceConfigStatics;
  
  class HoughFenceConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(HoughFenceConfig &config, const HoughFenceConfig &max, const HoughFenceConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const HoughFenceConfig &config1, const HoughFenceConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, HoughFenceConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const HoughFenceConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, HoughFenceConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const HoughFenceConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T HoughFenceConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (HoughFenceConfig::* field);

      virtual void clamp(HoughFenceConfig &config, const HoughFenceConfig &max, const HoughFenceConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const HoughFenceConfig &config1, const HoughFenceConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, HoughFenceConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const HoughFenceConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, HoughFenceConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const HoughFenceConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 10 "../cfg/Hough.cfg"
      double resolution;
//#line 11 "../cfg/Hough.cfg"
      int pixel_res;
//#line 12 "../cfg/Hough.cfg"
      double theta_res;
//#line 13 "../cfg/Hough.cfg"
      int accum_thresh;
//#line 14 "../cfg/Hough.cfg"
      int min_length;
//#line 15 "../cfg/Hough.cfg"
      int gap_length;
//#line 138 "/opt/ros/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("HoughFenceConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const HoughFenceConfig &__max__ = __getMax__();
      const HoughFenceConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const HoughFenceConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const HoughFenceConfig &__getDefault__();
    static const HoughFenceConfig &__getMax__();
    static const HoughFenceConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const HoughFenceConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void HoughFenceConfig::ParamDescription<std::string>::clamp(HoughFenceConfig &config, const HoughFenceConfig &max, const HoughFenceConfig &min) const
  {
    return;
  }

  class HoughFenceConfigStatics
  {
    friend class HoughFenceConfig;
    
    HoughFenceConfigStatics()
    {
//#line 10 "../cfg/Hough.cfg"
      __min__.resolution = 0.0001;
//#line 10 "../cfg/Hough.cfg"
      __max__.resolution = 1.0;
//#line 10 "../cfg/Hough.cfg"
      __default__.resolution = 0.01;
//#line 10 "../cfg/Hough.cfg"
      __param_descriptions__.push_back(HoughFenceConfig::AbstractParamDescriptionConstPtr(new HoughFenceConfig::ParamDescription<double>("resolution", "double", 0, "Meters/pixel of scan image", "", &HoughFenceConfig::resolution)));
//#line 11 "../cfg/Hough.cfg"
      __min__.pixel_res = 1;
//#line 11 "../cfg/Hough.cfg"
      __max__.pixel_res = 20;
//#line 11 "../cfg/Hough.cfg"
      __default__.pixel_res = 5;
//#line 11 "../cfg/Hough.cfg"
      __param_descriptions__.push_back(HoughFenceConfig::AbstractParamDescriptionConstPtr(new HoughFenceConfig::ParamDescription<int>("pixel_res", "int", 0, "Width of radius accumulator bin", "", &HoughFenceConfig::pixel_res)));
//#line 12 "../cfg/Hough.cfg"
      __min__.theta_res = 0.00872664625997;
//#line 12 "../cfg/Hough.cfg"
      __max__.theta_res = 1.57079632679;
//#line 12 "../cfg/Hough.cfg"
      __default__.theta_res = 0.0174532925199;
//#line 12 "../cfg/Hough.cfg"
      __param_descriptions__.push_back(HoughFenceConfig::AbstractParamDescriptionConstPtr(new HoughFenceConfig::ParamDescription<double>("theta_res", "double", 0, "Width of theta accumulator bin", "", &HoughFenceConfig::theta_res)));
//#line 13 "../cfg/Hough.cfg"
      __min__.accum_thresh = 0;
//#line 13 "../cfg/Hough.cfg"
      __max__.accum_thresh = 1000;
//#line 13 "../cfg/Hough.cfg"
      __default__.accum_thresh = 40;
//#line 13 "../cfg/Hough.cfg"
      __param_descriptions__.push_back(HoughFenceConfig::AbstractParamDescriptionConstPtr(new HoughFenceConfig::ParamDescription<int>("accum_thresh", "int", 0, "Accumulator threshold", "", &HoughFenceConfig::accum_thresh)));
//#line 14 "../cfg/Hough.cfg"
      __min__.min_length = 0;
//#line 14 "../cfg/Hough.cfg"
      __max__.min_length = 1000;
//#line 14 "../cfg/Hough.cfg"
      __default__.min_length = 100;
//#line 14 "../cfg/Hough.cfg"
      __param_descriptions__.push_back(HoughFenceConfig::AbstractParamDescriptionConstPtr(new HoughFenceConfig::ParamDescription<int>("min_length", "int", 0, "Minimum line length (pixels)", "", &HoughFenceConfig::min_length)));
//#line 15 "../cfg/Hough.cfg"
      __min__.gap_length = 0;
//#line 15 "../cfg/Hough.cfg"
      __max__.gap_length = 1000;
//#line 15 "../cfg/Hough.cfg"
      __default__.gap_length = 100;
//#line 15 "../cfg/Hough.cfg"
      __param_descriptions__.push_back(HoughFenceConfig::AbstractParamDescriptionConstPtr(new HoughFenceConfig::ParamDescription<int>("gap_length", "int", 0, "Maximum bridgable gap (pixels)", "", &HoughFenceConfig::gap_length)));
//#line 239 "/opt/ros/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<HoughFenceConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<HoughFenceConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    HoughFenceConfig __max__;
    HoughFenceConfig __min__;
    HoughFenceConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const HoughFenceConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static HoughFenceConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &HoughFenceConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const HoughFenceConfig &HoughFenceConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const HoughFenceConfig &HoughFenceConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const HoughFenceConfig &HoughFenceConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<HoughFenceConfig::AbstractParamDescriptionConstPtr> &HoughFenceConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const HoughFenceConfigStatics *HoughFenceConfig::__get_statics__()
  {
    const static HoughFenceConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = HoughFenceConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __HOUGHFENCERECONFIGURATOR_H__
