#!/usr/bin/env python

import roslib; roslib.load_manifest('automow_fence_detection')
import rospy

from sensor_msgs.msg import LaserScan

from fence_detection.hough_detector import HoughDetector

from dynamic_reconfigure.server import Server
from fence_detection.cfg import HoughFenceConfig

def config_callback(config, level):
	print config

if __name__ == '__main__':
	rospy.init_node('HoughFence', anonymous=True)

	srv = Server(HoughFenceConfig, config_callback)

	rospy.spin()